routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'locale'], function() {

    /**
     * Backend Routes
     * Namespaces indicate folder structure
     */

    Route::group(['laroute' => false, 'prefix' => 'admin', 'namespace' => 'Backend', 'as' => 'backend.'], function() {
        Route::get('login', ['uses' => 'AdminAuthController@getLogin'])->name('login');
        Route::post('login', ['uses' => 'AdminAuthController@postLogin'])->name('login.post');
        Route::get('logout', ['uses' => 'AdminAuthController@getLogout'])->name('logout');
        Route::get('forgot-password', ['uses' => 'AdminAuthController@forgotPassword'])->name('forgot-password');
        Route::post('forgot-password', ['uses' => 'AdminAuthController@forgotPasswordPost'])->name('forgot-password.post');
        Route::post('aareset-password', ['uses' => 'AdminAuthController@resetPasswordPost'])->name('reset-password.post');
        Route::get('aareset-password/{token}', ['uses' => 'AdminAuthController@resetPassword'])->name('reset-password');
    });

    Route::group(['laroute' => false, 'middleware' => 'Admin', 'prefix' => env('APP_ADMIN_PATH', 'admin'), 'namespace' => 'Backend', 'as' => 'backend.'], function() {
        includeRouteFiles(__DIR__.'/Backend/');
    });

    /* ----------------------------------------------------------------------- */

    /**
     * Frontend Routes
     * Namespaces indicate folder structure
     */


    /** Check if website is set to offline
     * If website is set to offline then check if user have permission to access the offline website or not
     * If no permission, display offline reason page
     * Set permission by use Usergroup and Roles in admin section
     */

    if(config('settings.site_offline'))
    {
        Route::group(['middleware' => 'auth'], function () {
            Route::group(['middleware' => 'role:allow_offline'], function() {
                Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
                    includeRouteFiles(__DIR__.'/Frontend/');
                });
            });
        });
    } else {
        Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
            includeRouteFiles(__DIR__.'/Frontend/');
        });
    }

    Auth::routes();
});

app/Radio.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-05-26
 * Time: 10:56
 */

namespace App;

use App\Traits\SanitizedRequest;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use DB;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Radio extends Model implements HasMedia
{
    use InteractsWithMedia, SanitizedRequest;

    protected $table = 'radio';

    protected $fillable = ['name', 'alt_name', 'description', 'meta_title', 'meta_description', 'meta_keywords', 'artworkId'];

    protected $select;

    public function __construct()
    {
        $this->select = ['radio.id', 'radio.name', 'radio.alt_name', 'radio.description', 'radio.meta_title', 'radio.meta_description', 'radio.meta_keywords', 'artworks.artworkUrl'];
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('sm')
            ->width(60)
            ->height(60)
            ->performOnCollections('artwork')->nonQueued();

        $this->addMediaConversion('md')
            ->width(120)
            ->height(120)
            ->performOnCollections('artwork')->nonQueued();

        $this->addMediaConversion('lg')
            ->width(300)
            ->height(300)
            ->performOnCollections('artwork')->nonQueued();
    }

    public function getArtworkUrlAttribute($value)
    {
        $media = $this->getFirstMedia('artwork');
        if(! $media) {
            return asset( 'common/default/song.png');
        } else {
            if($media->disk == 's3') {
                return $media->getTemporaryUrl(Carbon::now()->addMinutes(intval(config('settings.s3_signed_time', 5))),'lg');
            } else {
                return $media->getFullUrl('lg');
            }
        }
    }

    public function getPermalinkUrlAttribute($value)
    {
        return route('frontend.radio.browse.category', ['slug' => str_slug($this->attributes['alt_name'])]);
    }
}

app/Http/Controllers/Backend/AdminAuthController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-06-18
 * Time: 13:09
 */

namespace App\Http\Controllers\Backend;

use App\Playlist;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Hash;
use Response;
use DB;
use App\Song;
use Config;
use Image;
use Storage;
use App\Upload;
use View;
use Route;
use App\User;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Email;
use App\Role;

class AdminAuthController extends Controller
{
    private $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function getLogin()
    {
        if (auth()->check()) {
            //if is already logged in
            return redirect('admin');
        } else {
            return view('backend.login');
        }

    }

    public function postLogin()
    {

        $this->request->validate([
            'email' => 'required|string',
            'password' => 'required',
        ]);

        $login = [
            'email' => $this->request->input('email'),
            'password' => $this->request->input('password'),
        ];
        if (auth()->attempt($login, $this->request->input('remember'))) {
            if(Role::getValue('admin_access')) {
                return redirect('admin');
            } else {
                return redirect()->back()->with('status', 'failed')->with('message', trans('auth.failed'));
            }
        } else {
            return redirect()->back()->with('status', 'failed')->with('message', trans('auth.failed'));
        }
    }

    /**
     * action admin/logout
     * @return RedirectResponse
     */
    public function getLogout()
    {
        auth()->logout();
        return redirect()->route('backend.login');
    }

    public function forgotPassword()
    {
        return view('backend.forgot-password');
    }

    public function forgotPasswordPost(){

        $this->request->validate([
            'email' => 'string|email|exists:users',
        ]);

        $user = User::where('email',  $this->request->input('email'))->firstOrFail();

        $row = DB::table("password_resets")->select('email')->where('email', $user->email)->first();
        $token = Str::random(60);

        if(isset($row->email))
        {
            DB::table("password_resets")->where('email', $user->email)->update([
                'token' => $token,
                'created_at' => Carbon::now()

            ]);

        } else {
            DB::table("password_resets")->insert([
                'email' => $user->email,
                'token' => $token,
                'created_at' => Carbon::now()

            ]);
        }

        (new Email)->resetPassword($user, route('backend.reset-password', ['token' => $token]));

        return redirect()->back()->with('status', 'success')->with('message', trans('passwords.sent'));
    }

    public function resetPassword()
    {
        $row = DB::table("password_resets")->select('email')->where('token', $this->request->route('token'))->first();

        if(isset($row->email))
        {
            $user = User::where('email',  $row->email)->firstOrFail();
            /**
             * Log user in then show the change password form
             */
            auth()->login($user);
            return view('backend.reset-password');
        } else {
            return redirect()->route('backend.forgot-password')->with('status', 'failed')->with('message', trans('Your reset code is invalid or has expired.'));
        }
    }

    public function resetPasswordPost()
    {
        if(! auth()->check())
        {
            abort('403');
        }

        $this->request->validate([
            'password' => 'required|confirmed|min:6',
        ]);

        /**
         * Change user password
         */
        $user = auth()->user();
        $user->password = bcrypt($this->request->input('password'));
        $user->save();

        /**
         * Delete password reset token
         */
        DB::table("password_resets")->where('email', $user->email)->delete();

        return redirect()->route('backend.dashboard')->with('status', 'success')->with('message', __('passwords.reset'));
    }

    public function addSong(){
        $this->request->validate([
            'object_type' => 'required|string',
            'object_id' => 'required|int',
            'song_id' => 'required|int',
        ]);
        $object_type = $this->request->input('object_type');
        $object_id = $this->request->input('object_id');
        $song_id = $this->request->input('song_id');


        if($object_type == 'playlist')
        {
            try {
                DB::table('playlist_songs')->insert(
                    [ 'song_id' => $song_id, 'playlist_id' => $object_id ]
                );
            } catch (\Exception $e) {

            }
        } else if($object_type == 'album') {
            try {
                DB::table('album_songs')->insert(
                    [ 'song_id' => $song_id, 'album_id' => $object_id ]
                );
            } catch (\Exception $e) {

            }
        }

        return response()->json(Song::findOrFail($song_id));
    }

    public function removeSong(){
        $this->request->validate([
            'object_type' => 'required|string',
            'object_id' => 'required|int',
            'song_id' => 'required|int',
        ]);
        $object_type = $this->request->input('object_type');
        $object_id = $this->request->input('object_id');
        $song_id = $this->request->input('song_id');


        if($object_type == 'playlist')
        {
            DB::table('playlist_songs')
                ->where('playlist_id', $object_id)
                ->where('song_id', $song_id)
                ->delete();
        } else if($object_type == 'album') {
            DB::table('album_songs')
                ->where('album_id', $object_id)
                ->where('song_id', $song_id)
                ->delete();
        }

        return Response::json(array(
            'success' => true
        ), 200);
    }

    public function upload(){
        /**
         * Call upload function, set isAdminPanel = true to force script automatic general info from ID3
         */

        if($this->request->routeIs('backend.artist.upload.bulk'))
        {
            $song = (new Upload)->handle($this->request, $this->request->route('artistId'), null, true);
        }  elseif($this->request->routeIs('backend.album.upload.bulk'))
        {
            $song = (new Upload)->handle($this->request, null, $this->request->route('album_id'), true);
        } else {
            $song = (new Upload)->handle($this->request, null, null, true);
        }

        return response()->json($song);
    }

    public function editSong(){
        $this->request->validate([
            'id' => 'required|numeric',
            'title' => 'required|max:100',
            'artistIds' => 'required|array',
            'copyright' => 'nullable|string|max:100',
            'created_at' => 'nullable|date_format:m/d/Y|after:' . Carbon::now(),
        ]);

        $song = Song::withoutGlobalScopes()->findOrFail($this->request->input('id'));

        $artistIds = $this->request->input('artistIds');
        if(is_array($artistIds))
        {
            $song->artistIds = implode(",", $this->request->input('artistIds'));
        }

        if ($this->request->hasFile('artwork')) {
            $this->request->validate([
                'artwork' => 'required|image|mimes:jpeg,png,jpg,gif|max:' . config('settings.max_image_file_size')
            ]);
            $song->clearMediaCollection('artwork');
            $song->addMediaFromBase64(base64_encode(Image::make($this->request->file('artwork'))->fit(intval(config('settings.image_artwork_max', 500)),  intval(config('settings.image_artwork_max', 500)))->encode('jpg', config('settings.image_jpeg_quality', 90))->encoded))
                ->usingFileName(time(). '.jpg')
                ->toMediaCollection('artwork', config('settings.storage_artwork_location', 'public'));
        }

        $song->title = $this->request->input('title');
        $genre = $this->request->input('genre');
        $mood = $this->request->input('mood');

        if($this->request->input('created_at'))
        {
            $song->created_at = Carbon::parse($this->request->input('created_at'));
        }

        if(is_array($genre))
        {
            $song->genre = implode(",", $this->request->input('genre'));
        }

        if(is_array($mood))
        {
            $song->mood = implode(",", $this->request->input('mood'));
        }

        $song->copyright = $this->request->input('copyright');
        $song->save();

        return response()->json($song);

    }
}

app/Http/Controllers/Backend/ApiTesterController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-07-22
 * Time: 03:57
 */

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Backend\Encore\ApiTester;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use View;

class ApiTesterController extends Controller
{
    public function index(Request $request)
    {
        $tester = new ApiTester();

        $view = View::make('backend.api-tester.index')
            ->with('routes', $tester->getRoutes());

        if($request->ajax()) {
            $sections = $view->renderSections();
            return $sections['content'];
        }
        return $view;
    }
    public function handle(Request $request)
    {
        $method = $request->get('method');
        $uri = $request->get('uri');
        $user = $request->get('user');
        $all = $request->all();
        $keys = array_get($all, 'key', []);
        $vals = array_get($all, 'val', []);
        ksort($keys);
        ksort($vals);
        $parameters = [];
        foreach ($keys as $index => $key) {
            $parameters[$key] = array_get($vals, $index);
        }
        $parameters = array_filter($parameters, function ($key) {
            return $key !== '';
        }, ARRAY_FILTER_USE_KEY);
        $tester = new ApiTester();
        $response = $tester->call($method, $uri, $parameters, $user);
        unset($_POST['method'], $_POST['_token']);
        return [
            'status'    => true,
            'message'   => 'success',
            'data'      => $tester->parseResponse($response),
            'request_headers' => getallheaders(),
            'post_data' => $_POST
        ];
    }
}

app/Http/Controllers/Backend/BulkController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-05-25
 * Time: 20:58
 */

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

class BulkController
{
    public function index(Request $request)
    {
        return view('backend.bulk.index');
    }
}

app/Http/Controllers/Backend/EmailController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-05-25
 * Time: 21:01
 */

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use DB;
use App\Email;

class EmailController
{
    private $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function index()
    {
        $emails =  Email::paginate(20);
        return view('backend.email.index')->with('emails', $emails);
    }

    public function edit()
    {
        $email =  Email::findOrFail($this->request->route('id'));

        return view('backend.email.edit')->with('email', $email);
    }

    public function editPost()
    {
        $this->request->validate([
            'subject' => 'required|string',
            'content' => 'required|string',
        ]);

        $email = Email::findOrFail($this->request->route('id'));

        $email->subject = $this->request->input('subject');
        $email->content = $this->request->input('content');
        $email->save();

        return redirect()->route('backend.email')->with('status', 'success')->with('message', 'Email template successfully saved!');
    }
}

resources/views/backend/metatags/index.blade.php
@extends('backend.index')
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('backend.dashboard') }}">Control Panel</a>
        </li>
        <li class="breadcrumb-item active">Manage meta tags on the website</li>
    </ol>
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 border-0">
                    <button class="btn btn-link p-0 m-0" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <h6 class="m-0 font-weight-bold text-primary">Add New Page</h6>
                    </button>
                </div>
                <div class="card-body p-0">
                    <div class="accordion" id="collapseMetaTags">
                        <div id="collapseOne" class="collapse p-4" aria-labelledby="headingOne" data-parent="#collapseMetaTags">
                            <form role="form" method="post" action="" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group row">
                                    <label class="col-sm-4">URL
                                        <p class="small">Specify URL of the website for which you want to assign meta tags.</p>
                                    </label>
                                    <div class="col-sm-8">
                                        <input class="form-control" name="url" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4">Information</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" name="info">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4">Page title</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" name="title" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4">Page description
                                        <p class="small">Text that can be displayed on the search engine.</p>
                                    </label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" rows="2" name="description"></textarea>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4">Keywords</label>
                                    <div class="col-sm-8">
                                        {!! makeTagSelector('keywords[]', isset($metatag) && ! old('keywords') ? $metatag->meta_keywords : old('keywords')) !!}
                                    </div>
                                </div>
                                <div class="form-group row border-bottom">
                                    <label class="col-sm-4">Auto general keywords
                                        <p class="small">Automatically mass generate keywords (base on title and description) to maximise your search engine presence. .</p>
                                    </label>
                                    <div class="col-sm-8 col-9">
                                        <label class="switch">
                                            {!! makeCheckBox('auto_keyword', 0) !!}
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4">Page Artwork
                                        <p class="small mt-2">This will use for social share, if the page already contain an artwork this will overwrite the current one. For example song page will use this instead of song artwork.</p>
                                    </label>
                                    <div class="col-sm-8">
                                        <div class="input-group col-xs-12">
                                            <input type="file" name="artwork" class="file-selector" accept="image/*">
                                            <span class="input-group-addon"><i class="fas fa-fw fa-image"></i></span>
                                            <input type="text" class="form-control input-lg" disabled placeholder="Upload Image">
                                            <span class="input-group-btn">
                                                <button class="browse btn btn-primary input-lg" type="button"><i class="fas fa-fw fa-file"></i> Browse</button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" name="action" value="add">
                                <button type="submit" class="btn btn-primary">Create</button>
                                <button type="reset" class="btn btn-info">Reset</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Manage Titles, Descriptions, and Keywords</h6>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('backend.metatags.sort.post') }}">
                        @csrf
                        <table class="table table-striped table-sortable">
                            <thead>
                            <tr>
                                <th class="th-handle"></th>
                                <th class="th-priority">Priority</th>
                                <th class="th-priority">Image</th>
                                <th>Alternative name</th>
                                <th>Url</th>
                                <th>Description</th>
                                <th class="th-2action">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($metatags as $index => $metatag)
                                <tr data-id="{{ $metatag->id }}">
                                    <td><i class="handle fas fa-fw fa-arrows-alt"></i></td>
                                    <td><input type="hidden" name="metaIds[]" value="{{ $metatag->id }}"></td>
                                    <td><img src="{{ $metatag->artwork_url }}"/></td>

                                    <td>{{ $metatag->url }}</td>
                                    <td><span title="{{ url($metatag->url) }}">{{ url($metatag->url) }}</span></td>
                                    <td>{{ $metatag->info }}</td>
                                    <td>
                                        <a href="{{ route('backend.metatags.edit', ['id' => $metatag->id]) }}" class="row-button edit"><i class="fas fa-fw fa-edit"></i></a>
                                        <a href="{{ route('backend.metatags.delete', ['id' => $metatag->id]) }}" onclick="return confirm('Are you sure?')" class="row-button delete"><i class="fas fa-fw fa-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                    <div class="card mt-4 py-3 border-left-info">
                        <div class="card-body card-small">
                            <p class="mb-0">In this section you can assign meta tags for site pages. For example, you can assign specific values for meta tags for the trending/community page, rather than use general values from the engine settings. You can specify the address of the page for which you want to change meta tags, and also you can specify a URL group using the '*' character which stands for search by any set of characters. E.g., if you use /page/*/, then specified meta tags will be used for pages /page/1/, /page/2/, /page/any text/, etc.</p>
                        </div>
                    </div>
                    <div class="card mt-4 py-3 border-left-info">
                        <div class="card-body card-small">
                            <p>A meta tag is an HTML tag containing information for search engines about a specific website. Meta tags contain keywords or phrases alerting search engines of a website's content to be included in search results for users requesting related information.</p>
                            <p><strong>Title Tag</strong> — The title meta tag is the most important element in the site optimization process. Many search engines pay particular attention to keywords that occur in the title tag. As well, search engines generally display the title tag's contents in their site listings.</p>
                            <p><strong>Description Tag</strong> — The description meta tag defines site information a search engine displays when it lists the site. The description meta tag should concisely explain the nature and contents of the page.</p>
                            <p class="mb-0"><strong>Keywords Tag</strong> — The keywords meta tag lists the search keywords for a site. The keywords entered here should reflect any words or phrases Internet users might use to search for the site. Although many search engines have ceased to incorporate this tag into their ranking procedures, it's still a good idea to add this tag before submitting a page.</p>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
@endsection