routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'locale'], function() {

    /**
     * Backend Routes
     * Namespaces indicate folder structure
     */

    Route::group(['laroute' => false, 'prefix' => 'admin', 'namespace' => 'Backend', 'as' => 'backend.'], function() {
        Route::get('login', ['uses' => 'AdminAuthController@getLogin'])->name('login');
        Route::post('login', ['uses' => 'AdminAuthController@postLogin'])->name('login.post');
        Route::get('logout', ['uses' => 'AdminAuthController@getLogout'])->name('logout');
        Route::get('forgot-password', ['uses' => 'AdminAuthController@forgotPassword'])->name('forgot-password');
        Route::post('forgot-password', ['uses' => 'AdminAuthController@forgotPasswordPost'])->name('forgot-password.post');
        Route::post('aareset-password', ['uses' => 'AdminAuthController@resetPasswordPost'])->name('reset-password.post');
        Route::get('aareset-password/{token}', ['uses' => 'AdminAuthController@resetPassword'])->name('reset-password');
    });

    Route::group(['laroute' => false, 'middleware' => 'Admin', 'prefix' => env('APP_ADMIN_PATH', 'admin'), 'namespace' => 'Backend', 'as' => 'backend.'], function() {
        includeRouteFiles(__DIR__.'/Backend/');
    });

    /* ----------------------------------------------------------------------- */

    /**
     * Frontend Routes
     * Namespaces indicate folder structure
     */


    /** Check if website is set to offline
     * If website is set to offline then check if user have permission to access the offline website or not
     * If no permission, display offline reason page
     * Set permission by use Usergroup and Roles in admin section
     */

    if(config('settings.site_offline'))
    {
        Route::group(['middleware' => 'auth'], function () {
            Route::group(['middleware' => 'role:allow_offline'], function() {
                Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
                    includeRouteFiles(__DIR__.'/Frontend/');
                });
            });
        });
    } else {
        Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
            includeRouteFiles(__DIR__.'/Frontend/');
        });
    }

    Auth::routes();
});

app/Album.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-05-25
 * Time: 08:47
 */

namespace App;

use App\Scopes\ApprovedScope;
use App\Scopes\PublishedScope;
use App\Scopes\VisibilityScope;
use App\Traits\SanitizedRequest;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use DB;
use Auth;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Album extends Model implements HasMedia
{
    use InteractsWithMedia, SanitizedRequest;

    protected $appends = ['artwork_url', 'artists', 'permalink_url'];

    protected $hidden = ['media', 'user_id', 'artistIds', 'description', 'approved', 'created_at', 'updated_at'];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new VisibilityScope);
        static::addGlobalScope(new ApprovedScope);
        static::addGlobalScope(new PublishedScope);
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('sm')
            ->width(60)
            ->height(60)
            ->performOnCollections('artwork')->nonQueued();

        $this->addMediaConversion('md')
            ->width(120)
            ->height(120)
            ->performOnCollections('artwork')->nonQueued();

        $this->addMediaConversion('lg')
            ->width(300)
            ->height(300)
            ->performOnCollections('artwork')->nonQueued();
    }

    public function getArtworkUrlAttribute($value)
    {
        $media = $this->getFirstMedia('artwork');
        if(! $media) {
            return asset( 'common/default/album.png');
        } else {
            if($media->disk == 's3') {
                return $media->getTemporaryUrl(Carbon::now()->addMinutes(intval(config('settings.s3_signed_time', 5))),'lg');
            } else {
                return $media->getFullUrl('lg');
            }
        }
    }

    public function getArtistsAttribute()
    {
        return Artist::whereIn('id', explode(',', $this->attributes['artistIds']))->orderBy(DB::raw('FIELD(id, ' .  $this->attributes['artistIds']. ')', 'FIELD'))->get();
    }

    public function getMoodsAttribute()
    {
        return Mood::whereIn('id', explode(',', $this->attributes['mood']))->get();
    }

    public function getGenresAttribute($value)
    {

        $this->attributes['genres'] = Genre::whereIn('id', explode(',', $this->attributes['genre']))->get();

        return $this->attributes['genres'];
    }

    public function getPermalinkUrlAttribute($value)
    {
        return route('frontend.album', ['id' => $this->attributes['id'], 'slug' => str_slug($this->attributes['title'])]);
    }

    public function getSongCountAttribute($value)
    {
        return Song::leftJoin('album_songs', 'album_songs.song_id', '=', (new Song)->getTable() . '.id')
            ->where('album_songs.album_id', $this->id)
            ->count();
    }

    public function songs()
    {
        return Song::leftJoin('album_songs', 'album_songs.song_id', '=', (new Song)->getTable() . '.id')
            ->select('songs.*', 'album_songs.id as host_id')
            ->where('album_songs.album_id', $this->id)
            ->orderBy('album_songs.priority', 'asc');
    }

    public function getFavoriteAttribute($value) {
        if(auth()->check()){
            return Love::where('user_id', auth()->user()->id)->where('loveable_id', $this->id)->where('loveable_type', $this->getMorphClass())->exists();
        } else {
            return false;
        }
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function love()
    {
        return $this->morphOne(Love::class, 'loveable')->where('user_id', auth()->user()->id);
    }

    private function checkFavorite($album_id)
    {
        if(auth()->check()){
            $row = DB::table('loves')
                ->select('loves.id')
                ->where('loves.user_id', auth()->user()->id)
                ->where('loves.item_id', $album_id)
                ->where('loves.type', 3)
                ->first();

            if((Object) $row && isset($row->id)) {
                return true;
            } else {
                return false;
            }

        } else {
            return false;
        }
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function delete()
    {
        DB::table('album_songs')->where('album_id', $this->id)->delete();
        Comment::where('commentable_type', $this->getMorphClass())->where('commentable_id', $this->id)->delete();
        Love::where('loveable_type', $this->getMorphClass())->where('loveable_id', $this->id)->delete();
        Activity::where('activityable_type', $this->getMorphClass())->where('activityable_id', $this->id)->delete();

        return parent::delete();
    }
}

app/Http/Controllers/Backend/AdminAuthController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-06-18
 * Time: 13:09
 */

namespace App\Http\Controllers\Backend;

use App\Playlist;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Hash;
use Response;
use DB;
use App\Song;
use Config;
use Image;
use Storage;
use App\Upload;
use View;
use Route;
use App\User;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Email;
use App\Role;

class AdminAuthController extends Controller
{
    private $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function getLogin()
    {
        if (auth()->check()) {
            //if is already logged in
            return redirect('admin');
        } else {
            return view('backend.login');
        }

    }

    public function postLogin()
    {

        $this->request->validate([
            'email' => 'required|string',
            'password' => 'required',
        ]);

        $login = [
            'email' => $this->request->input('email'),
            'password' => $this->request->input('password'),
        ];
        if (auth()->attempt($login, $this->request->input('remember'))) {
            if(Role::getValue('admin_access')) {
                return redirect('admin');
            } else {
                return redirect()->back()->with('status', 'failed')->with('message', trans('auth.failed'));
            }
        } else {
            return redirect()->back()->with('status', 'failed')->with('message', trans('auth.failed'));
        }
    }

    /**
     * action admin/logout
     * @return RedirectResponse
     */
    public function getLogout()
    {
        auth()->logout();
        return redirect()->route('backend.login');
    }

    public function forgotPassword()
    {
        return view('backend.forgot-password');
    }

    public function forgotPasswordPost(){

        $this->request->validate([
            'email' => 'string|email|exists:users',
        ]);

        $user = User::where('email',  $this->request->input('email'))->firstOrFail();

        $row = DB::table("password_resets")->select('email')->where('email', $user->email)->first();
        $token = Str::random(60);

        if(isset($row->email))
        {
            DB::table("password_resets")->where('email', $user->email)->update([
                'token' => $token,
                'created_at' => Carbon::now()

            ]);

        } else {
            DB::table("password_resets")->insert([
                'email' => $user->email,
                'token' => $token,
                'created_at' => Carbon::now()

            ]);
        }

        (new Email)->resetPassword($user, route('backend.reset-password', ['token' => $token]));

        return redirect()->back()->with('status', 'success')->with('message', trans('passwords.sent'));
    }

    public function resetPassword()
    {
        $row = DB::table("password_resets")->select('email')->where('token', $this->request->route('token'))->first();

        if(isset($row->email))
        {
            $user = User::where('email',  $row->email)->firstOrFail();
            /**
             * Log user in then show the change password form
             */
            auth()->login($user);
            return view('backend.reset-password');
        } else {
            return redirect()->route('backend.forgot-password')->with('status', 'failed')->with('message', trans('Your reset code is invalid or has expired.'));
        }
    }

    public function resetPasswordPost()
    {
        if(! auth()->check())
        {
            abort('403');
        }

        $this->request->validate([
            'password' => 'required|confirmed|min:6',
        ]);

        /**
         * Change user password
         */
        $user = auth()->user();
        $user->password = bcrypt($this->request->input('password'));
        $user->save();

        /**
         * Delete password reset token
         */
        DB::table("password_resets")->where('email', $user->email)->delete();

        return redirect()->route('backend.dashboard')->with('status', 'success')->with('message', __('passwords.reset'));
    }

    public function addSong(){
        $this->request->validate([
            'object_type' => 'required|string',
            'object_id' => 'required|int',
            'song_id' => 'required|int',
        ]);
        $object_type = $this->request->input('object_type');
        $object_id = $this->request->input('object_id');
        $song_id = $this->request->input('song_id');


        if($object_type == 'playlist')
        {
            try {
                DB::table('playlist_songs')->insert(
                    [ 'song_id' => $song_id, 'playlist_id' => $object_id ]
                );
            } catch (\Exception $e) {

            }
        } else if($object_type == 'album') {
            try {
                DB::table('album_songs')->insert(
                    [ 'song_id' => $song_id, 'album_id' => $object_id ]
                );
            } catch (\Exception $e) {

            }
        }

        return response()->json(Song::findOrFail($song_id));
    }

    public function removeSong(){
        $this->request->validate([
            'object_type' => 'required|string',
            'object_id' => 'required|int',
            'song_id' => 'required|int',
        ]);
        $object_type = $this->request->input('object_type');
        $object_id = $this->request->input('object_id');
        $song_id = $this->request->input('song_id');


        if($object_type == 'playlist')
        {
            DB::table('playlist_songs')
                ->where('playlist_id', $object_id)
                ->where('song_id', $song_id)
                ->delete();
        } else if($object_type == 'album') {
            DB::table('album_songs')
                ->where('album_id', $object_id)
                ->where('song_id', $song_id)
                ->delete();
        }

        return Response::json(array(
            'success' => true
        ), 200);
    }

    public function upload(){
        /**
         * Call upload function, set isAdminPanel = true to force script automatic general info from ID3
         */

        if($this->request->routeIs('backend.artist.upload.bulk'))
        {
            $song = (new Upload)->handle($this->request, $this->request->route('artistId'), null, true);
        }  elseif($this->request->routeIs('backend.album.upload.bulk'))
        {
            $song = (new Upload)->handle($this->request, null, $this->request->route('album_id'), true);
        } else {
            $song = (new Upload)->handle($this->request, null, null, true);
        }

        return response()->json($song);
    }

    public function editSong(){
        $this->request->validate([
            'id' => 'required|numeric',
            'title' => 'required|max:100',
            'artistIds' => 'required|array',
            'copyright' => 'nullable|string|max:100',
            'created_at' => 'nullable|date_format:m/d/Y|after:' . Carbon::now(),
        ]);

        $song = Song::withoutGlobalScopes()->findOrFail($this->request->input('id'));

        $artistIds = $this->request->input('artistIds');
        if(is_array($artistIds))
        {
            $song->artistIds = implode(",", $this->request->input('artistIds'));
        }

        if ($this->request->hasFile('artwork')) {
            $this->request->validate([
                'artwork' => 'required|image|mimes:jpeg,png,jpg,gif|max:' . config('settings.max_image_file_size')
            ]);
            $song->clearMediaCollection('artwork');
            $song->addMediaFromBase64(base64_encode(Image::make($this->request->file('artwork'))->fit(intval(config('settings.image_artwork_max', 500)),  intval(config('settings.image_artwork_max', 500)))->encode('jpg', config('settings.image_jpeg_quality', 90))->encoded))
                ->usingFileName(time(). '.jpg')
                ->toMediaCollection('artwork', config('settings.storage_artwork_location', 'public'));
        }

        $song->title = $this->request->input('title');
        $genre = $this->request->input('genre');
        $mood = $this->request->input('mood');

        if($this->request->input('created_at'))
        {
            $song->created_at = Carbon::parse($this->request->input('created_at'));
        }

        if(is_array($genre))
        {
            $song->genre = implode(",", $this->request->input('genre'));
        }

        if(is_array($mood))
        {
            $song->mood = implode(",", $this->request->input('mood'));
        }

        $song->copyright = $this->request->input('copyright');
        $song->save();

        return response()->json($song);

    }
}

app/Http/Controllers/Backend/BulkController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-05-25
 * Time: 20:58
 */

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

class BulkController
{
    public function index(Request $request)
    {
        return view('backend.bulk.index');
    }
}

app/Http/Controllers/Backend/EmailController.php
<?php
/**
 * Created by NiNaCoder.
 * Date: 2019-05-25
 * Time: 21:01
 */

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use DB;
use App\Email;

class EmailController
{
    private $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function index()
    {
        $emails =  Email::paginate(20);
        return view('backend.email.index')->with('emails', $emails);
    }

    public function edit()
    {
        $email =  Email::findOrFail($this->request->route('id'));

        return view('backend.email.edit')->with('email', $email);
    }

    public function editPost()
    {
        $this->request->validate([
            'subject' => 'required|string',
            'content' => 'required|string',
        ]);

        $email = Email::findOrFail($this->request->route('id'));

        $email->subject = $this->request->input('subject');
        $email->content = $this->request->input('content');
        $email->save();

        return redirect()->route('backend.email')->with('status', 'success')->with('message', 'Email template successfully saved!');
    }
}

resources/views/backend/albums/edit.blade.php
@extends('backend.index')
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('backend.dashboard') }}">Control Panel</a>
        </li>
        <li class="breadcrumb-item"><a href="{{ route('backend.albums') }}">Albums</a></li>
        <li class="breadcrumb-item active"><a href="{{ route('backend.albums.edit', ['id' => $album->id]) }}">{{ $album->title }}</a> - @foreach($album->artists as $artist)<a href="{{ url('admin/artists/edit/' . $artist->id) }}" title="{{$artist->name}}">{{$artist->name}}</a>@if(!$loop->last), @endif @endforeach</li>
    </ol>
    <div class="row">
        <div class="col-lg-12 media-info mb-3 album">
            <div class="media mb-3">
                <img class="mr-3" src="{{ $album->artwork_url }}">
                <div class="media-body">
                    <h5 class="m-0">{{ $album->title }} - @foreach($album->artists as $artist)<a href="{{ route('backend.artists.edit', ['id' => $artist->id]) }}" title="{{$artist->name}}">{{$artist->name}}</a>@if(!$loop->last), @endif @endforeach</h5>
                    <p>Songs: {{ $album->song_count }}</p>
                    <p class="m-0"><a href="{{ $album->permalink_url }}" class="btn btn-warning" target="_blank">Preview @if(! $album->approved) (only Moderator) @endif</a> <a href="{{ route('backend.albums.tracklist', ['id' => $album->id]) }}" class="btn btn-info">Tracks List</a></p>
                </div>
            </div>
        </div>
        <div class="col-lg-12">

            <form role="form" method="post" action="" enctype="multipart/form-data">
                @csrf
                <div class="form-group multi-artists">
                    <label>Artists</label>
                    <select class="form-control multi-selector" data-ajax--url="{{ route('api.search.artist') }}" name="artistIds[]" multiple="">
                        @foreach ($album->artists as $index => $artist)
                            <option value="{{ $artist->id }}" selected="selected" data-artwork="{{ $artist->artwork_url }}" data-title="{{ $artist->name }}">{{ $artist->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Album Name</label>
                    <input name="name" class="form-control" value="{{ $album->title }}" required>
                </div>
                <div class="form-group">
                    <label>Artwork</label>
                    <div class="input-group col-xs-12">
                        <input type="file" name="artwork" class="file-selector" accept="image/*">
                        <span class="input-group-addon"><i class="fas fa-fw fa-image"></i></span>
                        <input type="text" class="form-control input-lg" disabled placeholder="Upload Image">
                        <span class="input-group-btn"><button class="browse btn btn-primary input-lg" type="button"><i class="fas fa-fw fa-file"></i> Browse</button></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <label class="switch">
                            {!! makeCheckBox('update-song-artwork') !!}
                            <span class="slider round"></span>
                        </label>
                        <label class="pl-6 col-form-label">Also update artwork for all songs in this album</label>
                    </div>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" rows="3" name="description">{{ $album->description }}</textarea>
                </div>
                <div class="form-group">
                    <label>Genre(s)</label>
                    <select multiple="" class="form-control select2-active" name="genre[]">
                        {!! genreSelection(explode(',', $album->genre)) !!}
                    </select>
                </div>
                <div class="form-group">
                    <label>Mood(s)</label>
                    <select multiple="" class="form-control select2-active" name="mood[]">
                        {!! moodSelection(explode(',', $album->mood)) !!}
                    </select>
                </div>
                <div class="form-group">
                    <label>Copyright</label>
                    <input type="text" class="form-control" name="copyright" value="{{ $album->copyright }}">
                </div>
                <div class="form-group">
                    <label>Released At</label>
                    <input type="text" class="form-control datepicker" name="released_at" value="{{ \Carbon\Carbon::parse($album->released_at)->format('m/d/Y') }}" autocomplete="off">
                </div>
                <div class="form-group">
                    <label>Schedule Publish</label>
                    <input type="text" class="form-control datepicker" name="created_at" value="{{ \Carbon\Carbon::parse($album->created_at)->format('m/d/Y') }}" autocomplete="off">
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <label class="switch">
                            {!! makeCheckBox('approved', $album->approved ) !!}
                            <span class="slider round"></span>
                        </label>
                        <label class="pl-6 col-form-label">Approve this album</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                @if(! $album->approved)
                    <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Reject</button>
                @endif
            </form>
            <div class="mt-5 collapse" id="collapseExample">
                <form role="form" method="post" action="{{ route('backend.albums.edit.reject.post', ['id' => $album->id]) }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Comment</label>
                        <textarea class="form-control" rows="3" name="comment"></textarea>
                    </div>
                    <button type="submit" class="btn btn-warning">Reject & Send Email to the artist</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/albums/tracklist.blade.php
@extends('backend.index')
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('backend.dashboard') }}">Control Panel</a>
        </li>
        <li class="breadcrumb-item"><a href="{{ route('backend.albums') }}">Albums</a></li>
        <li class="breadcrumb-item"><a href="{{ route('backend.albums.edit', ['id' => $album->id]) }}">{{ $album->title }}</a> - @foreach($album->artists as $artist)<a href="{{ url('admin/artists/edit/' . $artist->id) }}" title="{{$artist->name}}">{{$artist->name}}</a>@if(!$loop->last), @endif @endforeach</li>
        <li class="breadcrumb-item active">Tracks list</li>
    </ol>
    <div class="row">
        <div class="col-lg-12 media-info mb-3 album">
            <div class="media mb-3">
                <img class="mr-3" src="{{ $album->artwork_url }}">
                <div class="media-body">
                    <h5 class="m-0">{{ $album->title }} - @foreach($album->artists as $artist)<a href="{{ route('backend.artists.edit', ['id' => $artist->id]) }}" title="{{$artist->name}}">{{$artist->name}}</a>@if(!$loop->last), @endif @endforeach</h5>
                    <p>Songs: {{ $album->song_count }}</p>
                    <p class="m-0"><a href="{{ $album->permalink_url }}" class="btn btn-warning" target="_blank">Preview @if(! $album->approved) (only Moderator) @endif</a></p>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="box-suggest">
                <form method="get" id="suggest-form" data-object-type="album" data-object-id="{{ $album->id }}" action="{{ route('api.search.song') }}">
                    <div class="form-group input-group">
                        <input type="hidden" name="limit" value="5">
                        <input type="text" class="form-control suggest-tracks-form" name="q" placeholder="Add song to this album" autocomplete="off">
                    </div>
                </form>
                <div class="auto-suggest"></div>
            </div>
            <form id="mass-action-form" method="post" action="{{ route('backend.albums.tracklist.mass.action', ['id' => $album->id]) }}">
                @csrf
                <table class="table table-striped table-sortable">
                    <colgroup>
                        <col class="span1">
                        <col class="span7">
                    </colgroup>
                    <thead>
                    <tr>
                        <th class="th-handle"></th>
                        <th class="th-priority">Priority</th>
                        <th class="th-image"></th>
                        <th>Title <span title="Double click to edit" data-toggle="tooltip" data-placement="top">(?)</span></th>
                        <th class="desktop">Artist(s)</th>
                        <th class="desktop">Album</th>
                        <th class="desktop">Likes</th>
                        <th class="desktop">Plays</th>
                        <th class="desktop">Approved</th>
                        <th class="desktop">Extra</th>
                        <th class="th-2action">Action</th>
                        <th class="th-checkbox">
                            <label class="engine-checkbox">
                                <input id="check-all" class="multi-check-box" type="checkbox">
                                <span class="checkmark"></span>
                            </label>
                        </th>
                    </tr>
                    </thead>
                    <tbody id="song-row">
                        @include('backend.commons.song', ['songs' => $album->songs, 'sortOrder' => true])
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary mt-4">Save sort order</button>
                    </div>
                    <div class="col-6">
                        <div class="form-inline float-sm-right">
                            <div class="form-group mb-2">
                                <select name="action" class="form-control mr-2">
                                    <option value="">-- Action --</option>
                                    <option value="remove_from_album">Remove from this album</option>
                                    <option value="delete">Remove from this album & delete song</option>
                                </select>
                            </div>
                            <button id="start-mass-action" type="button" class="btn btn-primary mb-2">Start</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/backend/albums/upload.blade.php
@extends('backend.index')
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('backend.dashboard') }}">Control Panel</a></li>
        <li class="breadcrumb-item"><a href="{{ route('backend.albums') }}">Albums</a></li>
        <li class="breadcrumb-item"><a href="{{ url('admin/albums/edit/' . $album->id) }}">{{ $album->title }}</a></li>
        <li class="breadcrumb-item active">Upload</li>
    </ol>
    <div class="row">
        <div class="col-12">
            <div class="uploaded-files card-columns card-2-columns"></div>
            <form id="fileupload" method="POST" enctype="multipart/form-data" action="{{ route('backend.album.upload.bulk', ['album_id' => $album->id]) }}">
                <div class="upload-container">
                    <div id="upload-file-button" class="btn btn-primary btn-secondary">
                        <svg class="icon" height="26" width="18" viewBox="0 0 24 24"  xmlns="http://www.w3.org/2000/svg">
                            <path d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M9 16h6v-6h4l-7-7-7 7h4zm-4 2h14v2H5z"></path>
                        </svg>
                        <span data-translate-text="PLAY_PLAYLIST">Upload Your Music</span>
                        <input id="upload-file-input" type="file" accept="audio/*" name="file" multiple>
                    </div>
                    <p>Browse for files to upload or drag and drop them here</p>
                </div>
            </form>
        </div>
    </div>
    @include('backend.commons.upload-item')
@endsection